repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.750
    hooks:
      - id: mypy
        args: ['--strict']
        files: src
  - repo: https://github.com/psf/black
    rev: 19.10b0
    hooks:
      - id: black
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
      - id: flake8
        additional_dependencies: [
          "git+https://github.com/PyCQA/pyflakes#egg=pyflakes",
          "git+https://gitlab.com/PyCQA/pycodestyle#egg=pycodestyle",
          "flake8-import-order",
        ]
  - repo: https://github.com/PyCQA/pydocstyle
    rev: 4.0.1
    hooks:
      - id: pydocstyle
  - repo: https://github.com/asottile/setup-cfg-fmt
    rev: v1.6.0
    hooks:
      - id: setup-cfg-fmt
